### ISSUE TITLE
review & compare ensembleTax

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/chemtax#11]
Francisco Chavez mentioned the following Rpackage: https://github.com/dcat4/ensembleTax

The package looks very relevant. @sebastiandig : have you seen this package before?

**Comment by 7yl4r** [comment]
oops, nevermind. They used chemtax in connection with ensembleTax to write a paper: Catlett et al. in progress in oceanography

**Comment by sebastiandig** [comment]
@7yl4r 

This may not be relevant to CHEMTAX algorithm, but is relevant to eDNA and comparisons withCHEMTAX. Enrique and Luke Thompson might be interested in this.
